/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bb6d3439-5fbf-47f2-bb0b-7ae72e68af90",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Ao9lnt21U",
    "aws_user_pools_web_client_id": "1ivff891rh44473212hr3c5la7",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7ysjrsfuljdsdo32n632rqi5iu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
